[server]
port = 8501
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#22d3ee"
backgroundColor = "#0b1220"
secondBackgroundColor = "#121a2b"
textColor = "#e6f6ff"